name: 'Post to Steem'

on: [push]

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
      - name: 'Processor'
        uses: 'steemfans/process-issues-for-posting-to-steem-action@master'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: 'automation'
          owner: 'ety001'
