name: 'Post to Steem'

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  post_to_steem:
    runs-on: ubuntu-latest
    steps:
      - name: 'Processor'
        id: 'processor'
        uses: 'steemfans/process-issues-for-posting-to-steem-action@master'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          tz: 'Asia/Shanghai'
      - name: 'Post to Steem'
        id: post
        uses: 'steemfans/post-to-steem-action@master'
        if: steps.processor.outputs.issue_number != 0
        with:
          posting_key: ${{ secrets.POSTING_KEY }}
          title: ${{ steps.processor.outputs.title }}
          author: 'ety001.test'
          tags: ${{ steps.processor.outputs.tags }}
          content: ${{ steps.processor.outputs.content }}
          reward: ${{ steps.processor.outputs.reward }}
      - name: 'Close Issue'
        uses: 'steemfans/process-issues-for-posting-to-steem-action@master'
        if: steps.processor.outputs.issue_number != 0
        with:
          issue_number: ${{ steps.processor.outputs.issue_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
      - name: 'Send telegram message'
        uses: appleboy/telegram-action@master
        if: steps.processor.outputs.issue_number != 1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Hi, I have posted issue https://github.com/ety001/automation/issues/${{ steps.processor.outputs.issue_number }} to Steem.

