name: 'Post to Steem'

on: [push, workflow_dispatch]

jobs:
  post_to_steem:
    runs-on: ubuntu-latest
    steps:
      - name: 'Processor'
        id: 'processor'
        uses: 'steemfans/process-issues-for-posting-to-steem-action@master'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: 'automation'
          owner: 'ety001'
          tz: 'Asia/Shanghai'
      - name: 'Print Output'
        run: |
          echo "${{ steps.processor.outputs.issue_id }}"
          echo "${{ steps.processor.outputs.title }}"
          echo "${{ steps.processor.outputs.content }}"
          echo "${{ steps.processor.outputs.tags }}"
          echo "${{ steps.processor.outputs.reward }}"
