name: 'Test'

on:
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check TEST ENV
        id: check_test_env
        env:
          TEST1: ${{ secrets.TEST1 }}
          TEST2: ${{ secrets.TEST2 }}
        run: |
          echo "is_test_set: ${{ env.TEST1 != '' && env.TEST2 != '' }}"
          echo "::set-output name=is_test_set::${{ env.TEST1 != '' && env.TEST2 != '' }}"
      - name: 'Send telegram message'
        if: |
          steps.check_test_env.outputs.is_test_set == false
        run: |
          echo "${{ steps.check_test_env.outputs.is_test_set }}"
      - name: 'publish'
        uses: steemfans/post-to-steem-action@master
        with:
          posting_key: ${{ secrets.POSTING_KEY }}
          title: This is a test post to test steemjs
          author: ${{ secrets.USERNAME }}
          tags: 'test,test1'
          content: |
            # This is a test post from github action
            ok, fine! [https://github.com/steemfans/post-to-steem-action](https://github.com/steemfans/post-to-steem-action)
