name: 'Test Branch Name'

on:
  workflow_dispatch:

jobs:
  get_branch_name:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: |
          if [ ${GITHUB_REF_NAME} == 'master' ] || [ ${GITHUB_REF_NAME} == 'main' ]
          then
            echo "latest"
          else
            echo ${GITHUB_REF_NAME}
          fi
          echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_REF#refs/heads/}"
        id: extract_branch
