name: 'test'

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'Send telegram message'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            test (${{env.REPORT_DATE}})
