name: 'GitHub Actions Weather Bot'

on:
  schedule:
    - cron: '30 0 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: echo "OUTPUT=`./weather/run.sh`" >> $GITHUB_ENV
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'Send telegram message'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Zibo Weather Report (${{env.REPORT_DATE}})
            ${{env.OUTPUT}}
