name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '30 1 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash ./weatcher/run.sh
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: ${{ secrets.MAIL_HOST }}
          server_port: 25
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Zibo Weather Report (${{env.REPORT_DATE}})
          body: file://result.html
          to: weather@akawa.ink
          from: GitHub Actions
          content_type: text/html
